ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com/"
drosera_rpc = "https://relay.hoodi.drosera.io/"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.liquidity_drain_trap]
path = "out/LiquidityDrainTrap.sol/LiquidityDrainTrap.json"
response_contract = "0xBE7553DFe346BDb1F467a78FE006ecF3E178e311"
response_function = "respondToIncident(bytes)"
cooldown_period_blocks = 15
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 8
private_trap = false
